version: '3'

services:
  db:
    image: postgres:15
    env_file:
      - .env-prod
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./mooduck
    env_file:
      - .env-prod
    depends_on:
      - db
    volumes:
      - media:/app/media
    ports:
      - 8888:8000
    command: bash -c "aerich upgrade && gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"

volumes:
  pg_data:
  media:
    